# Generated by Django 4.0.4 on 2022-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimtable',
            name='No_of_doors',
            field=models.FloatField(default=0),
        ),
    ]
