# Generated by Django 4.0.4 on 2022-04-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0002_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='electrical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='general',
            name='electricalSqft',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='general',
            name='framingBulkhead',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='general',
            name='framingSqft',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
