# Generated by Django 4.0.4 on 2022-05-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0002_alter_trimtable_no_of_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='markup',
            name='Stairs_skirting',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitprice',
            name='Stairs_skirting',
            field=models.FloatField(default=0),
        ),
    ]
