# Generated by Django 4.0.4 on 2022-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0003_general_electrical_general_electricalsqft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dumpster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='electrical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='electricalSqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='framing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='framingBulkhead',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='framingSqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='permit',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='general',
        ),
    ]
