# Generated by Django 4.0.4 on 2022-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0003_markup_stairs_skirting_unitprice_stairs_skirting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanstable',
            name='Bar_Allowances',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Bathroom_Allowance',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Cabinetry',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Carpet',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Countertops',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Drywall',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Electrical_Final',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Electrical_Rough',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Final_Install_Punch_List',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Flooring',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Framing',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='HVAC',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Insulation',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Misc_Materials',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Painting',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Plumbing_Final',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Plumbing_Rough',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Tile',
        ),
        migrations.RemoveField(
            model_name='booleanstable',
            name='Trim',
        ),
        migrations.AlterField(
            model_name='generaldetailstable',
            name='Customer_Ease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generaldetailstable',
            name='Year_old',
            field=models.BooleanField(default=False),
        ),
    ]
