# Generated by Django 4.0.4 on 2022-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0004_remove_booleanstable_bar_allowances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanstable',
            name='Customer_Ease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booleanstable',
            name='Year_old',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GeneralDetailsTable',
        ),
    ]
