# Generated by Django 4.0.4 on 2022-04-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0005_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permit', models.PositiveIntegerField(default=50)),
                ('Dumpster', models.PositiveIntegerField(default=50)),
                ('Framing', models.PositiveIntegerField(default=50)),
                ('HVAC', models.PositiveIntegerField(default=50)),
                ('Plumbing_Rough', models.PositiveIntegerField(default=50)),
                ('Plumbing_Final', models.PositiveIntegerField(default=50)),
                ('Electrical_Rough', models.PositiveIntegerField(default=50)),
                ('Electrical_Final', models.PositiveIntegerField(default=50)),
                ('Insulation', models.PositiveIntegerField(default=50)),
                ('Drywall', models.PositiveIntegerField(default=50)),
                ('Trim', models.PositiveIntegerField(default=50)),
                ('Painting', models.PositiveIntegerField(default=50)),
                ('Cabinetry', models.PositiveIntegerField(default=50)),
                ('Countertops', models.PositiveIntegerField(default=50)),
                ('Tile', models.PositiveIntegerField(default=50)),
                ('Flooring', models.PositiveIntegerField(default=50)),
                ('Carpet', models.PositiveIntegerField(default=50)),
                ('Bathroom_Allowance', models.PositiveIntegerField(default=50)),
                ('Bar_Allowances', models.PositiveIntegerField(default=50)),
                ('Final_Install_Punch_List', models.PositiveIntegerField(default=50)),
                ('Misc_Materials', models.PositiveIntegerField(default=50)),
            ],
            options={
                'ordering': ['Permit'],
            },
        ),
        migrations.CreateModel(
            name='Unitprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permit', models.PositiveIntegerField(default=50)),
                ('Dumpster', models.PositiveIntegerField(default=50)),
                ('Framing', models.PositiveIntegerField(default=50)),
                ('HVAC', models.PositiveIntegerField(default=50)),
                ('Plumbing_Rough', models.PositiveIntegerField(default=50)),
                ('Plumbing_Final', models.PositiveIntegerField(default=50)),
                ('Electrical_Rough', models.PositiveIntegerField(default=50)),
                ('Electrical_Final', models.PositiveIntegerField(default=50)),
                ('Insulation', models.PositiveIntegerField(default=50)),
                ('Drywall', models.PositiveIntegerField(default=50)),
                ('Trim', models.PositiveIntegerField(default=50)),
                ('Painting', models.PositiveIntegerField(default=50)),
                ('Cabinetry', models.PositiveIntegerField(default=50)),
                ('Countertops', models.PositiveIntegerField(default=50)),
                ('Tile', models.PositiveIntegerField(default=50)),
                ('Flooring', models.PositiveIntegerField(default=50)),
                ('Carpet', models.PositiveIntegerField(default=50)),
                ('Bathroom_Allowance', models.PositiveIntegerField(default=50)),
                ('Bar_Allowances', models.PositiveIntegerField(default=50)),
                ('Final_Install_Punch_List', models.PositiveIntegerField(default=50)),
                ('Misc_Materials', models.PositiveIntegerField(default=50)),
            ],
            options={
                'ordering': ['Permit'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customerName']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='dumpster',
            new_name='Bar_Allowance_item1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='electrical',
            new_name='Bar_Allowance_item2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='framing',
            new_name='Bar_Allowance_item3',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='permit',
            new_name='Bar_Allowance_item4',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='electricalSqft',
            new_name='Casing_LF',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='framingBulkhead',
            new_name='Concrete_to_be_Broken',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='framingSqft',
            new_name='Customer_Ease',
        ),
        migrations.AddField(
            model_name='customer',
            name='Bar_Allowance_item5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bar_Allowance_items_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bar_Allowances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bathroom_Allowance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bathroom_Allowance_item1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bathroom_Allowance_item2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bathroom_Allowance_item3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bathroom_Allowance_item4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bathroom_Allowance_item5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Bathroom_Allowance_items_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Cabinetry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Carpet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Carpet_sqft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Cast_Iron_Pipe_Connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Ceiling_Texture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ConcreteRemoval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Countertop_sqft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Countertop_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Countertops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Dimmer_Switches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Dishwater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Drywall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Drywall_sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Dumpster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Electrical_Final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Electrical_Rough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Electrical_sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Fan_Install',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Final_Install_Punch_List',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Final_install',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Floor_sqft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Flooring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Framing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Framing_LF_of_Bulkheads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Framing_LF_of_Walls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='HVAC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='HVAC_RSE_Vents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Insulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Insulation_sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='LF_of_Cabinetry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='LF_of_Underground',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='LF_of_baseboard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item1_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item2_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item3_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item4_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Allowance_item5_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Misc_Materials',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='No_of_doors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Paint_sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Painting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Panel_Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Permit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Plumbing_Correct_Location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Plumbing_Final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Plumbing_Rough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Refigerator_Water_Line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Rough_In_Water_Lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Set_Toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Sink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Solid_core_doors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='SubPanel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Tile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Tile_Backsplash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Tile_Backsplash_sqft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Tile_Shower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Tile_Shower_sqft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Tile_floor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Tile_floor_sqft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Trim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Trim_Out_Fixtures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Undercabinet_Lighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Vanity_Faucet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='Wall_Texture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Year_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='add_colors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='customerEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
