# Generated by Django 4.0.4 on 2022-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0006_remove_markup_tile_backsplash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanstable',
            name='Permit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
