# Generated by Django 4.0.4 on 2022-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0006_markup_unitprice_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Misc_Materials_val',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Misc_Materials',
            field=models.BooleanField(default=False),
        ),
    ]
