# Generated by Django 4.0.4 on 2022-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0010_alter_customer_bathroom_allowance_items_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Bar_Allowance_items_type',
            field=models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3'), ('4', 'None')], default=4, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Bathroom_Allowance_items_type',
            field=models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3'), ('4', 'None')], default=4, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Ceiling_Texture',
            field=models.CharField(choices=[('1', 'Knockdown'), ('2', 'Others')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Countertop_type',
            field=models.CharField(choices=[('1', 'Granite'), ('2', 'Quartz'), ('3', 'ButcherBlock')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Drywall_sqft',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Wall_Texture',
            field=models.CharField(choices=[('1', 'Orange Peel'), ('2', 'Others')], default=1, max_length=20),
        ),
    ]
