from django.contrib import admin
from .models import Customer

# Register your models here.
@admin.register(Customer)
class PostAdmin(admin.ModelAdmin):
    list_display = [
        'projectManager',
        'customerName',
        'customerAddress',
        'customerContact',
        'customerEmail',
        'Permit',
    'Dumpster',
    'Framing',
    'HVAC',
    'Plumbing_Rough',
    'Plumbing_Final',
    'Electrical_Rough',
    'Electrical_Final',
    'Insulation',
    'Drywall',
    'Trim',
    'Painting',
    'Cabinetry',
    'Countertops',
    'Tile',
    'Flooring',
    'Carpet',
    'Bathroom_Allowance',
    'Bar_Allowances',
    'Final_Install_Punch_List',
    'Misc_Materials',
    'Year_old',
    'Customer_Ease',
    'Framing_LF_of_Walls',
    'Framing_LF_of_Bulkheads',
    'HVAC_RSE_Vents',
    'Cast_Iron_Pipe_Connection',
    'ConcreteRemoval',
    'Plumbing_Correct_Location',
    'LF_of_Underground',                 
    'Concrete_to_be_Broken',
    'Rough_In_Water_Lines',
    'Set_Toilet',
    'Trim_Out_Fixtures',
    'Vanity_Faucet',
    'Dishwater',
    'Sink',
    'Refigerator_Water_Line',
    'Electrical_sqft',
    'Panel_Location',
    'Dimmer_Switches',
    'Undercabinet_Lighting',
    'SubPanel',
    'Fan_Install',
    'Insulation_sqft',
    'Drywall_sqft',
    'Wall_Texture',
    'Ceiling_Texture',
    'LF_of_Cabinetry',
    'LF_of_baseboard',
    'Casing_LF',
    'Solid_core_doors',
    'Paint_sqft',
    'add_colors',
    'Countertop_type',
    'Countertop_sqft',
    'Tile_floor',
    'Tile_Backsplash',
    'Tile_Shower',
    'Floor_sqft',
    'Carpet_sqft',
    'Bathroom_Allowance_items_type',
    'Bathroom_Allowance_item1',
    'Bathroom_Allowance_item2',
    'Bathroom_Allowance_item3',
    'Bathroom_Allowance_item4',
    'Bathroom_Allowance_item5',
    'Bar_Allowance_items_type',
    'Bar_Allowance_item1',
    'Bar_Allowance_item2',
    'Bar_Allowance_item3',
    'Bar_Allowance_item4',
    'Bar_Allowance_item5',
    'Misc_Allowance_item1',
    'Misc_Allowance_item2',
    'Misc_Allowance_item3',
    'Misc_Allowance_item4',
    'Misc_Allowance_item5',
    'Misc_Allowance_item1_no',
    'Misc_Allowance_item2_no',
    'Misc_Allowance_item3_no',
    'Misc_Allowance_item4_no',
    'Misc_Allowance_item5_no',
    'Final_install',
    'Misc_Materials']





