# Generated by Django 4.0.4 on 2022-04-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit', models.BooleanField()),
                ('dumpster', models.BooleanField()),
                ('framing', models.BooleanField()),
                ('general_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basement.customer')),
            ],
        ),
    ]
