# Generated by Django 4.0.4 on 2022-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0007_customer_misc_materials_val_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
