# Generated by Django 4.0.4 on 2022-04-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0009_alter_customer_customeraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Bathroom_Allowance_items_type',
            field=models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3')], default=1, max_length=20),
        ),
    ]
