# Generated by Django 4.0.4 on 2022-04-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0011_alter_customer_bar_allowance_items_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Drywall_sqft',
            field=models.IntegerField(default=0),
        ),
    ]
